#ifndef _PACKET_CONSTANTS_
#define _PACKET_CONSTANTS_

#define KILOBYTE 1024
#define MEGABYTE 1024*1024
#define GIGABYTE 1024*1024*1024
#define MAX_FILE_PATH_LENGTH 100
#define MAX_BUFFER_SIZE MEGABYTE


#define PACKET 0
#define FILE_PACKET 1
#define FILE_CONFIG_PACKET 2
#define REQUEST_PACKET 3
#define RESPONSE_PACKET 4



#endif