FROM martinsimango/filecopierbase:ARM_latest

FROM scratch 

EXPOSE 3000

WORKDIR /app
COPY --from=0 /go/bin/go-server go-server
COPY --from=0 /go-server-dylibs/* /lib/

ENTRYPOINT ["/app/go-server"]
