version: 2.1

jobs:
  build:
    # working_directory: ~/circleci-filecopier
    # docker:
    #   - image: "circleci/python:3.6.4"
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: ls && make clean install
  # test:
  #   working_directory: ~/circleci-python
  #   docker:
  #     - image: "circleci/python:3.6.4"
  #   steps:
  #     - checkout
  #     - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build