version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build-arm:
          context: DOCKER
      - build-x86_64:
          context: DOCKER
jobs:
  build-arm:
    working_directory: ~/filecopier
    # docker:
    #   - image: "golang:1.16-alpine"
    machine:
      image: ubuntu-2004:202101-01
      resource_class: arm.medium
    steps:
      - checkout
      - run: |
          sudo snap install go --classic
      #log into docker
      - run: |
          docker login --username martinsimango --password $DOCKER_PASS
      # build the application image
      - run: make docker-build-arm

     # deploy the image
      - run: make docker-push-arm

  build-x86_64:
    working_directory: ~/filecopier
    # docker:
    #   - image: "golang:1.16-alpine"
    machine:
      image: ubuntu-2004:202101-01
      resource_class: medium
    steps:
      - checkout
      - run: |
          sudo snap install go --classic
      #log into docker
      - run: |
          docker login --username martinsimango --password $DOCKER_PASS
      # build the application image
      - run: make docker-build-x86_64

     # deploy the image
      - run: make docker-push-x86_64
    