version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: DOCKER
jobs:
  build:
    working_directory: ~/filecopier
    # docker:
    #   - image: "golang:1.16-alpine"
    machine:
      image: ubuntu-2004:202101-01
      resource_class: arm.medium
    steps:
      - checkout
      - run: |
          sudo snap install go --classic
          sudo make clean install
      #log into docker
      - run: |
          docker login --username martinsimango --password $DOCKER_PASS
      # build the application image
      - run: make docker-build-arm

     # deploy the image
      - run: make docker-push-arm

  # test:
  #   working_directory: ~/circleci-python
  #   docker:
  #     - image: "circleci/python:3.6.4"
  #   steps:
  #     - checkout
  #     - run: python3 main-test.py

# workflows:
#   build_and_test:
#     jobs:
#       - build
#          context: DOCKER
#       # - test:
      #     requires:
      #       - build