version: 2.1

jobs:
  build:
    working_directory: ~/filecopier
    docker:
      - image: "golang:1.16-alpine"
    # machine:
    #   image: ubuntu-2004:202101-01
    # resource_class: arm.medium
    steps:
      - checkout
      - run: |
          apk update && apk add --no-cache git
          apk add build-base
          make clean install
      #log into docker
      - run: |
        echo "$DOCKER_PASS" | docker login --username martinsimango --password-stdin
      # build the application image
      - run: make docker-build-x86_64

     # deploy the image
      - run: make docker-push-x86_64

  # test:
  #   working_directory: ~/circleci-python
  #   docker:
  #     - image: "circleci/python:3.6.4"
  #   steps:
  #     - checkout
  #     - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build